name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v3
      with:
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Release APK
      run: flutter build apk --release
      working-directory: ${{ github.workspace }}
      
    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Build Debug APK
      run: flutter build apk --debug
      working-directory: ${{ github.workspace }}

    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
